set tool "clic"
set exp_internal 1
set testdata {

  {"e"      "2.718282" }
  {"PI"     "3.141593" }

  {"1+2"    "3.000000"}
  {"(-1)+2"   "1.000000"}
  {"(-3)+-3"  "-6.000000"}
  {"1000000000000000000000 + 1000000000000000000000"   "2000000000000000000000.000000"}

  {"2-1"    "1.000000"}
  {"1-3"    "-2.000000"}
  {"(-2)--2"  "0.000000"}

  {"2*2"    "4.000000"}
  {"3*0"    "0.000000"}
  {"(-2)*2"    "-4.000000"}
  {"(-2)*-2"  "4.000000"}

  {"6/3"    "2.000000"}
  {"3/0"    "inf"     }
  {"0/2"    "0.000000"}
  {"(-2)/3"   "-0.666667"}

  {"2^3"    "8.000000"}
  {"(2)"    "2.000000"}
  {"(2+2)*3" "12.000000"}
  {"(3*(2-2)+(4/2))" "2.000000" }

  {"neg(4)"  "-4.000000"}
  {"neg(-4)"  "4.000000"}
  {"sin(3)"  "0.141120"}
  {"cos(3)"  "-0.989992"}
  {"tg(4)"   "1.157821"}
  {"arcsin(1)" "1.570796"}
  {"arcsin(5)" "nan"}
  {"arccos(-1)" "3.141593"}
  {"arctg(1)"   "0.785398"}
  {"exp(2)"     "7.389056"}
  {"ln(2)"      "0.693147"}
  {"ln(0)"      "-inf"    }

  {"lg(3)"      "0.477121"}
  {"sqrt(4)"    "2.000000"}
  {"sqrt(-2)"   "-nan"}
  {"sqrt(5)"    "2.236068"}
  {"cbrt(8)"    "2.000000"}
  {"sh(4)"      "27.289917"}
  {"ch(4)"      "27.308233"}
  {"th(4)"      "0.999329"}
  {"erf(2)"     "0.995322"}
  {"erfc(2)"    "0.004678"}
  {"G(3)"       "2.000000"}

  {"(2"     "---syntax error"}
  {"tan(2)"  "---unknown identifier"}

  {"\\h"    ".*quit" }
  {"\\v"    "e =.*" }
  {"\\f"    ".*G.*" }
  {"\\c"    "" }
  {"\\g"    "---unknown command" }
  {""       ""}

  {"1==2"   "---more than one '='" }
  {"1=2"    "---invalid variable or function name"}
  {"a=2"    "2.000000" }
}

global CLIC
foreach pattern $testdata {
  set inputs [lindex $pattern 0]
  append inputs "\r"
  spawn $CLIC
  expect "clic2>" { send "$inputs"}

  expect {
    -re [lindex $pattern 1] {
      pass $inputs
    }
    default { fail $inputs }
    eof { puts "End of file reached" }
  }
  expect "clic2>" { send "\\q\r"}
}

spawn $CLIC
expect "clic2>" { send "\\q\r"}
expect {
  eof        { puts "End of file reached" }
}
